url: http://liamfish77.github.io
baseurl: ""

# Site Settings
title: Liam Fisher
description: "Liam Fisher Homepage"
keywords: "Liam Fisher, Philosophy, Drum, Lawrence, Spanish, Coffee"
collections:
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
markdown: kramdown
highlighter: rouge
exclude: ["Rakefile", "LICENSE", "readme.md"]
